output = "./internal/musicapp/db/pgmodel"
pkgname = "models"
no-tests = true

[mysql]
dbname  = "musicapp"
host    = "127.0.0.1"
port    = 3306
user    = "user"
pass    = "userpass"
sslmode = "false"
